import RequestProject.Basic
import RequestProject.FamilyMatrix

/-!
# The construction `eq:construction`

Let `K ⊆ F` be fields with `F / K` Galois with cyclic Galois group of order `n` generated by
`σ` (in the paper `K = 𝔽_q`, `F = 𝔽_{q^n}` and `σ (x) = x ^ (q ^ s)` for a unit `s` modulo
`n`).  For `w ∈ K` with `w ^ 2 - w + 1 = 0` the paper defines

`x *_{w,s} y = σ x · σ² y + σ x · σ⁻¹ y + σ⁻² x · σ⁻¹ y
                 + w (σ² x · σ y + σ⁻¹ x · σ y + σ⁻¹ x · σ⁻² y).`

This file defines this multiplication (`famMul`), relates it to the split matrix `LwM`
of `RequestProject.FamilyMatrix`, and proves the division property.
-/

namespace Semifields

open scoped BigOperators
open Matrix

section Sigma

variable {K F : Type*} [Field K] [Field F] [Algebra K F]
variable {n : ℕ} [NeZero n] (σ : F ≃ₐ[K] F)

/-- The power `σ ^ i` indexed by `i : ZMod n`; well defined once `σ ^ n = 1`. -/
def sig (i : ZMod n) : F ≃ₐ[K] F := σ ^ i.val

variable {σ}

omit [NeZero n] in
lemma pow_mod_of_pow_eq_one (hσ : σ ^ n = 1) (a : ℕ) : σ ^ (a % n) = σ ^ a := by
  conv_rhs => rw [← Nat.div_add_mod a n]
  rw [pow_add, pow_mul, hσ, one_pow, one_mul]

omit [NeZero n] in
@[simp] lemma sig_zero : sig (n := n) σ 0 = 1 := by simp [sig]

lemma sig_add (hσ : σ ^ n = 1) (i j : ZMod n) :
    sig σ (i + j) = (sig σ i : F ≃ₐ[K] F) * sig σ j := by
  simp only [sig]
  rw [ZMod.val_add, pow_mod_of_pow_eq_one hσ, pow_add]

lemma sig_add_apply (hσ : σ ^ n = 1) (i j : ZMod n) (x : F) :
    sig σ (i + j) x = sig σ i (sig σ j x) := by
  rw [sig_add hσ]
  rfl

omit [NeZero n] in
lemma sig_algebraMap (i : ZMod n) (c : K) : sig σ i (algebraMap K F c) = algebraMap K F c :=
  AlgEquiv.commutes _ _

omit [NeZero n] in
lemma sig_ne_zero {i : ZMod n} {x : F} (hx : x ≠ 0) : sig σ i x ≠ 0 := by
  simpa using fun h => hx ((sig σ i).injective (by simpa using h))

end Sigma

section Family

variable {K F : Type*} [Field K] [Field F] [Algebra K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F}

/-- The multiplication `eq:construction` of the family `𝒫_{w,s}`. -/
def famMul (n : ℕ) [NeZero n] (σ : F ≃ₐ[K] F) (w : K) (x y : F) : F :=
  sig σ (1 : ZMod n) x * sig σ (2 : ZMod n) y + sig σ (1 : ZMod n) x * sig σ (-1 : ZMod n) y
    + sig σ (-2 : ZMod n) x * sig σ (-1 : ZMod n) y
    + algebraMap K F w * (sig σ (2 : ZMod n) x * sig σ (1 : ZMod n) y
        + sig σ (-1 : ZMod n) x * sig σ (1 : ZMod n) y
        + sig σ (-1 : ZMod n) x * sig σ (-2 : ZMod n) y)

/-- The conjugate-coordinate embedding `Φ_σ (x) = (x, σ x, …, σ^{n-1} x)`. -/
def Phi (n : ℕ) [NeZero n] (σ : F ≃ₐ[K] F) (x : F) : ZMod n → F := fun i => sig σ i x

lemma Phi_eq_zero_iff (x : F) : Phi n σ x = 0 ↔ x = 0 := by
  constructor
  · intro h
    have := congrFun h 0
    simpa [Phi] using this
  · rintro rfl
    funext i
    simp [Phi]

lemma Phi_ne_zero {x : F} (hx : x ≠ 0) (i : ZMod n) : Phi n σ x i ≠ 0 := sig_ne_zero hx

/-- `eq:actual-family` : the split matrix at the conjugate coordinates of `x` computes the
multiplication. -/
theorem LwM_mulVec_Phi (hσ : σ ^ n = 1) (w : K) (x y : F) :
    (LwM (algebraMap K F w) (Phi n σ x)).mulVec (Phi n σ y) = Phi n σ (famMul n σ w x y) := by
  funext i
  rw [LwM_mulVec]
  simp only [Phi, famMul]
  have e1 : ∀ (j : ZMod n) (z : F), sig σ (i + j) z = sig σ i (sig σ j z) := fun j z =>
    sig_add_apply hσ i j z
  have e2 : ∀ (j : ZMod n) (z : F), sig σ (i - j) z = sig σ i (sig σ (-j) z) := by
    intro j z
    rw [sub_eq_add_neg, e1]
  simp only [e1, e2, map_add, map_mul, sig_algebraMap]

end Family


section Lambda

variable {K : Type*} [Field K]

/-- The scalar `λ_n(w) = (1 + w^n)^2 (1 - w^{2n})` of `eq:leftdet`. -/
def lam (w : K) (n : ℕ) : K := (1 + w ^ n) ^ 2 * (1 - w ^ (2 * n))

variable {w : K} (hw : w ^ 2 - w + 1 = 0)
include hw

lemma w_cube : w ^ 3 = -1 := by linear_combination (w + 1) * hw

lemma w_six : w ^ 6 = 1 := by
  have h := w_cube hw
  calc w ^ 6 = (w ^ 3) ^ 2 := by ring
  _ = 1 := by rw [h]; ring

lemma pow_eq_pow_mod_six (m : ℕ) : w ^ m = w ^ (m % 6) := by
  conv_lhs => rw [← Nat.div_add_mod m 6]
  rw [pow_add, pow_mul, w_six hw, one_pow, one_mul]

/-- `eq:lambda`, first case. -/
lemma lam_eq_of_mod_one {n : ℕ} (hn : n % 6 = 1) : lam w n = 3 * (1 + w) := by
  have h1 : w ^ n = w := by rw [pow_eq_pow_mod_six hw n, hn, pow_one]
  have h2 : w ^ (2 * n) = w ^ 2 := by
    rw [pow_eq_pow_mod_six hw (2 * n), show (2 * n) % 6 = 2 by omega]
  rw [lam, h1, h2]
  linear_combination (-w ^ 2 - 3 * w - 2) * hw

/-- `eq:lambda`, second case. -/
lemma lam_eq_of_mod_five {n : ℕ} (hn : n % 6 = 5) : lam w n = 3 * (2 - w) := by
  have h1 : w ^ n = w ^ 5 := by rw [pow_eq_pow_mod_six hw n, hn]
  have h2 : w ^ (2 * n) = w ^ 4 := by
    rw [pow_eq_pow_mod_six hw (2 * n), show (2 * n) % 6 = 4 by omega]
  have h5 : w ^ 5 = 1 - w := by linear_combination (w ^ 3 + w ^ 2 - 1) * hw
  have h4 : w ^ 4 = -w := by linear_combination (w ^ 2 + w) * hw
  rw [lam, h1, h2, h5, h4]
  linear_combination (w - 2) * hw

/-- The scalar of `eq:leftdet` is nonzero: this is where `q ≡ 1 (mod 3)`, i.e. the
characteristic being different from three, is used. -/
lemma lam_ne_zero (h3 : (3 : K) ≠ 0) {n : ℕ} (hn : n % 6 = 1 ∨ n % 6 = 5) : lam w n ≠ 0 := by
  rcases hn with hn | hn
  · rw [lam_eq_of_mod_one hw hn]
    refine mul_ne_zero h3 ?_
    intro hcon
    have hwv : w = -1 := by linear_combination hcon
    rw [hwv] at hw
    apply h3
    linear_combination hw
  · rw [lam_eq_of_mod_five hw hn]
    refine mul_ne_zero h3 ?_
    intro hcon
    have hwv : w = 2 := by linear_combination -hcon
    rw [hwv] at hw
    apply h3
    linear_combination hw

end Lambda

section Division

variable {K F : Type*} [Field K] [Field F] [Algebra K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F} {w : K}

/-- The split left determinant of the family, evaluated at the conjugate coordinates of a
nonzero element: this is `λ_n(w) · N_{F/K}(x)`. -/
theorem det_LwM_Phi (hw : w ^ 2 - w + 1 = 0) (hodd : Odd n) (h3 : 3 ≤ n) {x : F} (hx : x ≠ 0) :
    (LwM (algebraMap K F w) (Phi n σ x)).det
      = algebraMap K F (lam w n) * ∏ i, Phi n σ x i := by
  have hw' : (algebraMap K F w) ^ 2 - (algebraMap K F w) + 1 = 0 := by
    rw [← map_pow, ← map_one (algebraMap K F), ← map_sub, ← map_add, ← map_zero (algebraMap K F)]
    exact congrArg _ (by linear_combination hw)
  rw [det_LwM_of_ne_zero (fun i => Phi_ne_zero hx i) hw' hodd h3]
  congr 1
  rw [lam]
  push_cast
  ring

/-- The family has no zero divisors: `thm:division`. -/
theorem famMul_eq_zero_iff (hσ : σ ^ n = 1) (hw : w ^ 2 - w + 1 = 0) (h3 : (3 : K) ≠ 0)
    (hn : n % 6 = 1 ∨ n % 6 = 5) (hn5 : 5 ≤ n) {x y : F} (hxy : famMul n σ w x y = 0) :
    x = 0 ∨ y = 0 := by
  by_cases hx : x = 0
  · exact Or.inl hx
  refine Or.inr ?_
  have hodd : Odd n := by rcases hn with h | h <;> [skip; skip] <;> exact ⟨n / 2, by omega⟩
  have hdet : (LwM (algebraMap K F w) (Phi n σ x)).det ≠ 0 := by
    rw [det_LwM_Phi hw hodd (by omega) hx]
    refine mul_ne_zero ?_ (Finset.prod_ne_zero_iff.mpr (fun i _ => Phi_ne_zero hx i))
    simpa using lam_ne_zero hw h3 hn
  have hmul : (LwM (algebraMap K F w) (Phi n σ x)).mulVec (Phi n σ y) = 0 := by
    rw [LwM_mulVec_Phi hσ, hxy]
    funext i
    simp [Phi]
  have : Phi n σ y = 0 := by
    have hunit : IsUnit (LwM (algebraMap K F w) (Phi n σ x)).det := Ne.isUnit hdet
    have := congrArg (fun v => (LwM (algebraMap K F w) (Phi n σ x))⁻¹.mulVec v) hmul
    simpa [Matrix.mulVec_mulVec, Matrix.nonsing_inv_mul _ hunit] using this
  exact (Phi_eq_zero_iff y).mp this

/-- The multiplication of the family, as a `K`-bilinear map. -/
def famMulₗ (n : ℕ) [NeZero n] (σ : F ≃ₐ[K] F) (w : K) : F →ₗ[K] F →ₗ[K] F :=
  LinearMap.mk₂ K (famMul n σ w)
    (fun x₁ x₂ y => by simp only [famMul, map_add]; ring)
    (fun c x y => by
      simp only [famMul, Algebra.smul_def, map_mul, sig_algebraMap]; ring)
    (fun x y₁ y₂ => by simp only [famMul, map_add]; ring)
    (fun c x y => by
      simp only [famMul, Algebra.smul_def, map_mul, sig_algebraMap]; ring)

@[simp] lemma famMulₗ_apply (x y : F) : famMulₗ n σ w x y = famMul n σ w x y := rfl

/-- **Theorem `thm:division`, division part.** The family is a presemifield. -/
theorem isPresemifield_famMul (hσ : σ ^ n = 1) (hw : w ^ 2 - w + 1 = 0) (h3 : (3 : K) ≠ 0)
    (hn : n % 6 = 1 ∨ n % 6 = 5) (hn5 : 5 ≤ n) :
    IsPresemifield K (famMulₗ n σ w) where
  eq_zero_or_eq_zero := fun _ _ h => famMul_eq_zero_iff hσ hw h3 hn hn5 h
  exists_ne_zero := ⟨1, one_ne_zero⟩

end Division

end Semifields
