import RequestProject.GTFGeneral
import RequestProject.NucleiIsotopes

/-!
# Corollary `cor:menichetti`

Let `q = p ^ e ≡ 1 (mod 3)` be a prime power and let `r ≥ 5` be prime; put `K = 𝔽_q` and
`F = 𝔽_{q^r}`.  The family `𝒫_{w,s}` with `n = r` (`w` a root of `X² - X + 1` in `K`, `s` a
unit modulo `r`, i.e. `σ = x ↦ x^{q^s}` a generator of `Gal(F/K)`) represents exactly

* `r - 1` isotopy classes if `p ≡ 1 (mod 3)`,
* `(r - 1) / 2` isotopy classes if `p ≡ 2 (mod 3)`

of semifields of order `q^r`.  Every such semifield has centre and all three nuclei of order
`q`, and none is isotopic to a finite field or to an Albert generalized twisted field.

* `cor_menichetti` : the corollary, for arbitrary finite fields `K ⊆ F` with `[F : K] = r` and
  `|K| ≡ 1 (mod 3)`;
* `menichetti_threshold_false` : for every prime `r ≥ 5` and every characteristic `p ≠ 3` there
  are such semifields over arbitrarily large base fields `𝔽_q`, `q = p^e`, so no increase of the
  base-field threshold repairs the prime-dimensional classification (Menichetti's Corollary 33);
* `kaplansky_counterexample` : the case `r = 5` (Kaplansky's conjecture).

Isotopy is the general (additive) isotopy of `def:isotopy`.  The isotopy class of `𝒫_{w,s}` is
the class of the pair `(w, σ)` under `famIsotopySetoid`.
-/

namespace Semifields

open scoped BigOperators

section Roots

variable {K : Type*} [Field K] {p : ℕ} [Fact p.Prime] [CharP K p]

/-- The characteristic `p` of a field with `3 ≠ 0` is `≡ 1` or `≡ 2 (mod 3)`. -/
lemma char_mod_three (h3 : (3 : K) ≠ 0) : p % 3 = 1 ∨ p % 3 = 2 := by
  have hp := (Fact.out : p.Prime)
  have : p % 3 ≠ 0 := by
    intro h0
    have hdvd : 3 ∣ p := Nat.dvd_of_mod_eq_zero h0
    have hp3 : p = 3 := ((Nat.prime_dvd_prime_iff_eq Nat.prime_three hp).mp hdvd).symm
    apply h3
    have := CharP.cast_eq_zero K p
    rw [hp3] at this
    exact_mod_cast this
  omega

lemma frob_neg_root {w : K} : (-w) ^ p = -(w ^ p) := by
  have := (frobenius K p).map_neg w
  simpa [frobenius_def] using this

/-- If `p ≡ 1 (mod 3)`, the roots of `X² - X + 1` lie in the prime field, so they are fixed by
every power of the Frobenius. -/
lemma root_frob_of_mod_one (hp : p % 3 = 1) {w : K} (hw : w ^ 2 - w + 1 = 0) (j : ℕ) :
    w ^ p ^ j = w := by
  have hω : (-w) ^ 3 = 1 := by linear_combination (-w - 1) * hw
  have h1 : w ^ p = w := by
    have : (-w) ^ p = -w := by
      rw [← Nat.div_add_mod p 3, hp, pow_add, pow_mul, hω, one_pow, one_mul, pow_one]
    rw [frob_neg_root] at this
    exact neg_inj.mp this
  induction j with
  | zero => simp
  | succ j ih => rw [pow_succ, pow_mul, ih, h1]

/-- If `p ≡ 2 (mod 3)`, the Frobenius exchanges the two roots of `X² - X + 1`. -/
lemma root_frob_of_mod_two (hp : p % 3 = 2) {w : K} (hw : w ^ 2 - w + 1 = 0) :
    w ^ p = 1 - w := by
  have hω : (-w) ^ 3 = 1 := by linear_combination (-w - 1) * hw
  have : (-w) ^ p = (-w) ^ 2 := by
    rw [← Nat.div_add_mod p 3, hp, pow_add, pow_mul, hω, one_pow, one_mul]
  rw [frob_neg_root] at this
  linear_combination -this - hw

end Roots

section Generators

variable {K F : Type*} [Field K] [Fintype K] [Field F] [Finite F] [Algebra K F]
  {r : ℕ} [NeZero r]

/-- The Galois group of `F / K` is cyclic, generated by the `q`-Frobenius. -/
lemma exists_generator_of_finrank (hfin : Module.finrank K F = r) :
    ∃ σ : F ≃ₐ[K] F, Function.Bijective (fun i : ZMod r => sig σ i) := by
  set φ := FiniteField.frobeniusAlgEquivOfAlgebraic K F
  have hb := FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow K F
  rw [hfin] at hb
  refine ⟨φ, fun i j hij => ?_, fun g => ?_⟩
  · simp only [sig] at hij
    have := hb.1 (a₁ := ⟨i.val, ZMod.val_lt i⟩) (a₂ := ⟨j.val, ZMod.val_lt j⟩) hij
    exact ZMod.val_injective _ (congrArg Fin.val this)
  · obtain ⟨m, hm⟩ := hb.2 g
    refine ⟨(m.1 : ZMod r), ?_⟩
    simp only [sig]
    rw [ZMod.val_natCast, Nat.mod_eq_of_lt m.2]
    exact hm

omit [Fintype K] [Finite F] [NeZero r] in
/-- Every generator of `Gal(F / K)` is a power `σ ^ u` of a fixed one, with `u ≠ 0`. -/
lemma eq_sig_of_generator [Fintype (F ≃ₐ[K] F)] (hr : 1 < r) {σ τ : F ≃ₐ[K] F}
    (hσ : Function.Bijective (fun i : ZMod r => sig σ i))
    (hτ : Function.Bijective (fun i : ZMod r => sig τ i)) :
    ∃ u : ZMod r, u ≠ 0 ∧ τ = sig σ u := by
  obtain ⟨u, hu⟩ := hσ.2 τ
  refine ⟨u, ?_, hu.symm⟩
  rintro rfl
  haveI : Fact (1 < r) := ⟨hr⟩
  have h01 : sig τ (0 : ZMod r) = sig τ (1 : ZMod r) := by
    simp only [sig_zero]
    rw [← hu]
    simp [sig, ZMod.val_one]
  exact zero_ne_one (hτ.1 h01)

end Generators

section Isotopy

variable {F : Type*} [Field F] [Finite F] {p : ℕ} [Fact p.Prime] [CharP F p]

/-- Every multiplication is isotopic to its Galois twists (the isotopism is `(φ, φ, φ)`). -/
lemma isotopic_twistMul (j : ℕ) (mul : F → F → F) : Isotopic mul (twistMul p j mul) := by
  refine ⟨(iterateFrobeniusEquiv F p j).toAddEquiv, (iterateFrobeniusEquiv F p j).toAddEquiv,
    (iterateFrobeniusEquiv F p j).toAddEquiv, fun x y => ?_⟩
  change iterateFrobeniusEquiv F p j (mul ((iterateFrobeniusEquiv F p j).symm
    (iterateFrobeniusEquiv F p j x)) ((iterateFrobeniusEquiv F p j).symm
    (iterateFrobeniusEquiv F p j y))) = iterateFrobeniusEquiv F p j (mul x y)
  rw [RingEquiv.symm_apply_apply, RingEquiv.symm_apply_apply]

end Isotopy

section Parameters

variable (K F : Type*) [Field K] [Field F] [Algebra K F] (r : ℕ) [NeZero r]

/-- The parameters of the family `𝒫_{w,s}` with `n = r`: a root `w ∈ K` of `X² - X + 1`, and a
generator `σ` of `Gal(F / K)` (in the paper `σ (x) = x ^ (q ^ s)` with `s` a unit modulo `r`). -/
def FamParam : Type _ :=
  {x : K × (F ≃ₐ[K] F) // x.1 ^ 2 - x.1 + 1 = 0 ∧ Function.Bijective (fun i : ZMod r => sig x.2 i)}

/-- Isotopy of the corresponding members `𝒫_{w,s}` of the family, as an equivalence relation
on the parameters; its classes are the isotopy classes represented by the family. -/
def famIsotopySetoid : Setoid (FamParam K F r) where
  r a b := Isotopic (famMul r a.1.2 a.1.1) (famMul r b.1.2 b.1.1)
  iseqv := ⟨fun _ => Isotopic.refl _, Isotopic.symm, Isotopic.trans⟩

end Parameters

section Count

/-- Nonzero residues modulo `r` are the numbers `1, …, r - 1`. -/
lemma exists_fin_eq_of_ne_zero {r : ℕ} [NeZero r] {u : ZMod r} (hu : u ≠ 0) :
    ∃ i : Fin (r - 1), (((i : ℕ) + 1 : ℕ) : ZMod r) = u := by
  have hpos : 0 < u.val := Nat.pos_of_ne_zero (fun h => hu ((ZMod.val_eq_zero u).mp h))
  have hlt := ZMod.val_lt u
  refine ⟨⟨u.val - 1, by omega⟩, ?_⟩
  simp only
  rw [Nat.sub_add_cancel hpos, ZMod.natCast_zmod_val]

/-- Every nonzero residue modulo an odd `r` is `± k` with `1 ≤ k ≤ (r - 1) / 2`. -/
lemma exists_fin_half_eq_of_ne_zero {r : ℕ} [NeZero r] (hodd : r % 2 = 1) {u : ZMod r}
    (hu : u ≠ 0) :
    ∃ i : Fin ((r - 1) / 2), (((i : ℕ) + 1 : ℕ) : ZMod r) = u ∨
      (((i : ℕ) + 1 : ℕ) : ZMod r) = -u := by
  have hpos : 0 < u.val := Nat.pos_of_ne_zero (fun h => hu ((ZMod.val_eq_zero u).mp h))
  have hlt := ZMod.val_lt u
  by_cases hsmall : u.val ≤ (r - 1) / 2
  · refine ⟨⟨u.val - 1, by omega⟩, Or.inl ?_⟩
    simp only
    rw [Nat.sub_add_cancel hpos, ZMod.natCast_zmod_val]
  · refine ⟨⟨r - u.val - 1, by omega⟩, Or.inr ?_⟩
    simp only
    have e : r - u.val - 1 + 1 = r - u.val := by omega
    rw [e, Nat.cast_sub hlt.le, ZMod.natCast_self, ZMod.natCast_zmod_val, zero_sub]

lemma natCast_succ_ne_zero {r : ℕ} [NeZero r] {m : ℕ} (hm : m + 1 < r) :
    ((m + 1 : ℕ) : ZMod r) ≠ 0 := by
  intro h
  rw [ZMod.natCast_eq_zero_iff] at h
  exact absurd (Nat.le_of_dvd (by omega) h) (by omega)

lemma natCast_succ_inj {r : ℕ} [NeZero r] {a b : ℕ} (ha : a + 1 < r) (hb : b + 1 < r)
    (h : ((a + 1 : ℕ) : ZMod r) = ((b + 1 : ℕ) : ZMod r)) : a = b := by
  have := congrArg ZMod.val h
  rw [ZMod.val_natCast, ZMod.val_natCast, Nat.mod_eq_of_lt ha, Nat.mod_eq_of_lt hb] at this
  omega

lemma natCast_succ_ne_neg {r : ℕ} [NeZero r] {a b : ℕ} (hab : a + b + 2 < r)
    (h : ((a + 1 : ℕ) : ZMod r) = -((b + 1 : ℕ) : ZMod r)) : False := by
  have h' : (((a + 1) + (b + 1) : ℕ) : ZMod r) = 0 := by
    push_cast at h ⊢
    linear_combination h
  rw [ZMod.natCast_eq_zero_iff] at h'
  exact absurd (Nat.le_of_dvd (by omega) h') (by omega)

variable {K F : Type*} [Field K] [Fintype K] [Field F] [Fintype F] [Algebra K F]
  {p : ℕ} [Fact p.Prime] [CharP K p] {r : ℕ} [NeZero r]

/-- **The number of isotopy classes represented by the family** (`eq:classcount` with
`φ(r) = r - 1`, the count in `cor:menichetti`). -/
theorem card_famIsotopyClasses (hr : r.Prime) (hr5 : 5 ≤ r) (hq : Fintype.card K % 3 = 1)
    (hfin : Module.finrank K F = r) :
    Nat.card (Quotient (famIsotopySetoid K F r)) = if p % 3 = 1 then r - 1 else (r - 1) / 2 := by
  haveI : CharP F p := charP_of_injective_algebraMap (algebraMap K F).injective p
  haveI : Fact r.Prime := ⟨hr⟩
  have h3 : (3 : K) ≠ 0 := three_ne_zero_of_card_mod_three hq
  obtain ⟨w₀, hw₀⟩ := exists_w_of_card_mod_three hq
  obtain ⟨σ₀, hσ₀⟩ := exists_generator_of_finrank (K := K) (F := F) hfin
  have hσ₀r : σ₀ ^ r = 1 := pow_eq_one_of_bij hσ₀
  have hr1 : 1 < r := by omega
  -- the generator `σ₀ ^ u`, `u ≠ 0`
  have hgen : ∀ u : ZMod r, u ≠ 0 → Function.Bijective (fun i : ZMod r => sig (sig σ₀ u) i) :=
    fun u hu => bijective_sig_sig_unit hσ₀ u (Ne.isUnit hu)
  let mk : (u : ZMod r) → u ≠ 0 → FamParam K F r := fun u hu => ⟨(w₀, sig σ₀ u), hw₀, hgen u hu⟩
  -- `(w, σ₀ ^ u)` is isotopic to `(w₀, σ₀ ^ u)` or `(w₀, σ₀ ^ (-u))`
  have hneg : ∀ u : ZMod r, sig (sig σ₀ u) (-1 : ZMod r) = sig σ₀ (-u) := fun u => by
    rw [sig_sig hσ₀r]; ring_nf
  have hswap : ∀ (u : ZMod r) (hu : u ≠ 0),
      Isotopic (famMul r (sig σ₀ u) (1 - w₀)) (famMul r (sig σ₀ (-u)) w₀) := by
    intro u hu
    have := (isotopicLin_famMul_neg_one (pow_eq_one_of_bij (hgen u hu)) hw₀).toIsotopic
    rwa [hneg] at this
  have hcases : ∀ x : FamParam K F r, ∃ u : ZMod r, ∃ hu : u ≠ 0,
      (famIsotopySetoid K F r) x (mk u hu) ∨ (famIsotopySetoid K F r) x (mk (-u) (neg_ne_zero.mpr hu)) := by
    rintro ⟨⟨w, σ⟩, hw, hσ⟩
    obtain ⟨u, hu, rfl⟩ := eq_sig_of_generator hr1 hσ₀ hσ
    refine ⟨u, hu, ?_⟩
    by_cases hww : w = w₀
    · subst hww; left; exact Isotopic.refl _
    · right
      have e := root_eq_one_sub hw hw₀ hww
      subst e
      exact hswap u hu
  have hmod := char_mod_three (p := p) h3
  -- classification of isotopies between the representatives
  have hiso : ∀ (u v : ZMod r) (hu : u ≠ 0) (hv : v ≠ 0),
      (famIsotopySetoid K F r) (mk u hu) (mk v hv) → v = u ∨ v = -u := by
    intro u v hu hv h
    obtain ⟨j, hj1, hj2⟩ := famMul_isotopic_cases (p := p) hr hr5 hq (hgen u hu) (hgen v hv)
      hw₀ hw₀ h
    by_cases hwj : w₀ ^ p ^ j = w₀
    · left; exact hσ₀.1 (hj1 hwj)
    · right
      have := hj2 hwj
      rw [hneg] at this
      exact hσ₀.1 this
  split_ifs with hp1
  · -- `p ≡ 1 (mod 3)`: the classes are the generators
    have hiso1 : ∀ (u v : ZMod r) (hu : u ≠ 0) (hv : v ≠ 0),
        (famIsotopySetoid K F r) (mk u hu) (mk v hv) → v = u := by
      intro u v hu hv h
      obtain ⟨j, hj1, -⟩ := famMul_isotopic_cases (p := p) hr hr5 hq (hgen u hu) (hgen v hv)
        hw₀ hw₀ h
      exact hσ₀.1 (hj1 (root_frob_of_mod_one hp1 hw₀ j))
    let rep : Fin (r - 1) → Quotient (famIsotopySetoid K F r) := fun i =>
      ⟦mk (((i : ℕ) + 1 : ℕ) : ZMod r) (natCast_succ_ne_zero (by omega))⟧
    rw [← Nat.card_eq_of_bijective rep ⟨fun i j hij => ?_, fun c => ?_⟩, Nat.card_eq_fintype_card,
      Fintype.card_fin]
    · have := hiso1 _ _ (natCast_succ_ne_zero (m := (i : ℕ)) (by omega))
        (natCast_succ_ne_zero (m := (j : ℕ)) (by omega)) (Quotient.exact hij)
      exact Fin.ext (natCast_succ_inj (by omega) (by omega) this).symm
    · induction c using Quotient.inductionOn with
      | h x =>
        obtain ⟨u, hu, hx | hx⟩ := hcases x
        · obtain ⟨i, hi⟩ := exists_fin_eq_of_ne_zero hu
          refine ⟨i, Quotient.sound ?_⟩
          simp only [hi]
          exact Isotopic.symm hx
        · obtain ⟨i, hi⟩ := exists_fin_eq_of_ne_zero (neg_ne_zero.mpr hu)
          refine ⟨i, Quotient.sound ?_⟩
          simp only [hi]
          exact Isotopic.symm hx
  · -- `p ≡ 2 (mod 3)`: `σ` and `σ⁻¹` give isotopic members
    have hp2 : p % 3 = 2 := by omega
    have hpm : ∀ (u : ZMod r) (hu : u ≠ 0),
        (famIsotopySetoid K F r) (mk u hu) (mk (-u) (neg_ne_zero.mpr hu)) := by
      intro u hu
      have h1 : Isotopic (famMul r (sig σ₀ u) w₀) (famMul r (sig σ₀ u) (1 - w₀)) := by
        have := isotopic_twistMul (p := p) 1 (famMul r (sig σ₀ u) w₀)
        rwa [twistMul_famMul, pow_one, root_frob_of_mod_two hp2 hw₀] at this
      exact h1.trans (hswap u hu)
    let rep : Fin ((r - 1) / 2) → Quotient (famIsotopySetoid K F r) := fun i =>
      ⟦mk (((i : ℕ) + 1 : ℕ) : ZMod r) (natCast_succ_ne_zero (by omega))⟧
    rw [← Nat.card_eq_of_bijective rep ⟨fun i j hij => ?_, fun c => ?_⟩, Nat.card_eq_fintype_card,
      Fintype.card_fin]
    · rcases hiso _ _ (natCast_succ_ne_zero (m := (i : ℕ)) (by omega))
        (natCast_succ_ne_zero (m := (j : ℕ)) (by omega)) (Quotient.exact hij) with h | h
      · exact Fin.ext (natCast_succ_inj (by omega) (by omega) h).symm
      · exact (natCast_succ_ne_neg (by omega) h).elim
    · induction c using Quotient.inductionOn with
      | h x =>
        obtain ⟨u, hu, hx⟩ := hcases x
        have hx' : (famIsotopySetoid K F r) x (mk u hu) := by
          rcases hx with hx | hx
          · exact hx
          · have := hpm (-u) (neg_ne_zero.mpr hu)
            simp only [neg_neg] at this
            exact Isotopic.trans hx this
        have hodd : r % 2 = 1 := by
          rcases Nat.even_or_odd r with he | ho
          · exfalso
            have := hr.eq_one_or_self_of_dvd 2 (even_iff_two_dvd.mp he)
            omega
          · exact Nat.odd_iff.mp ho
        obtain ⟨i, hi | hi⟩ := exists_fin_half_eq_of_ne_zero hodd hu
        · refine ⟨i, Quotient.sound ?_⟩
          simp only [hi]
          exact Isotopic.symm hx'
        · refine ⟨i, Quotient.sound ?_⟩
          simp only [hi]
          exact Isotopic.symm (Isotopic.trans hx' (hpm u hu))

end Count

section Transport

universe u v

/-- A multiplication isotopic to a generalized twisted field on some field `L` is isotopic to a
generalized twisted field on `F` (the two fields have the same finite order, hence are
isomorphic). -/
lemma isotopic_gtf_transport {F : Type u} {L : Type v} [Field F] [Finite F] [Field L]
    {mulP : F → F → F} {c : L} {τ υ : L ≃+* L}
    (h : Isotopic mulP (fun a b : L => a * b - c * τ a * υ b)) :
    ∃ (c' : F) (τ' υ' : F ≃+* F), Isotopic mulP (fun a b : F => a * b - c' * τ' a * υ' b) := by
  obtain ⟨A, -, -, -⟩ := id h
  haveI : Finite L := Finite.of_equiv F A.toEquiv
  letI := Fintype.ofFinite F
  letI := Fintype.ofFinite L
  have hcard : Fintype.card L = Fintype.card F := by
    rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card]
    exact (Nat.card_congr A.toEquiv).symm
  let e : L ≃+* F := FiniteField.ringEquivOfCardEq hcard
  refine ⟨e c, e.symm.trans (τ.trans e), e.symm.trans (υ.trans e),
    h.trans ⟨e.toAddEquiv, e.toAddEquiv, e.toAddEquiv, fun x y => ?_⟩⟩
  simp only [RingEquiv.toAddEquiv_eq_coe, RingEquiv.coe_toAddEquiv,
    RingEquiv.coe_trans, Function.comp_apply, RingEquiv.symm_apply_apply, map_sub, map_mul]

end Transport

section Corollary

universe v

variable {K F : Type*} [Field K] [Fintype K] [Field F] [Fintype F] [Algebra K F]
  {r : ℕ} [NeZero r]

/-- **Corollary `cor:menichetti`.**
Let `K = 𝔽_q` be a finite field of characteristic `p` with `q ≡ 1 (mod 3)`, let `r ≥ 5` be prime
and let `F = 𝔽_{q^r}` (any field extension of `K` of degree `r`).  Then:

* the family `𝒫_{w,s}` with `n = r` represents exactly `r - 1` isotopy classes if
  `p ≡ 1 (mod 3)` and `(r - 1) / 2` isotopy classes if `p ≡ 2 (mod 3)` (the classes of the
  parameters `(w, σ)` under isotopy of the members);
* these have order `|F| = q^r`, and each member is a presemifield, isotopic to the semifield
  `famSemi r σ w` given by Kaplansky's trick;
* every semifield multiplication on `F` isotopic to a member has centre and left, middle and
  right nuclei of order `q`;
* no member is isotopic to a finite field, nor to any generalized twisted field
  `x y - c τ(x) υ(y)` (`c` arbitrary, `τ, υ` arbitrary automorphisms) on any field; this
  includes all Albert generalized twisted fields.

Isotopy is the general (additive) isotopy of `def:isotopy`. -/
theorem cor_menichetti (p : ℕ) [Fact p.Prime] [CharP K p] (hr : r.Prime) (hr5 : 5 ≤ r)
    (hq : Fintype.card K % 3 = 1) (hfin : Module.finrank K F = r) :
    Nat.card (Quotient (famIsotopySetoid K F r)) = (if p % 3 = 1 then r - 1 else (r - 1) / 2) ∧
    Nat.card F = Fintype.card K ^ r ∧
    ∀ x : FamParam K F r,
      IsPresemifield K (famMulₗ r x.1.2 x.1.1) ∧
      IsSemifield (famSemi r x.1.2 x.1.1) ∧
      Isotopic (famMul r x.1.2 x.1.1) (famSemi r x.1.2 x.1.1) ∧
      (∀ S : F → F → F, IsSemifield S → Isotopic (famMul r x.1.2 x.1.1) S →
        Nat.card (semifieldCentre S) = Fintype.card K ∧
        Nat.card (leftNucleus S) = Fintype.card K ∧
        Nat.card (middleNucleus S) = Fintype.card K ∧
        Nat.card (rightNucleus S) = Fintype.card K) ∧
      (∀ (L : Type v) [Field L], ¬ Isotopic (famMul r x.1.2 x.1.1) (fun a b : L => a * b)) ∧
      (∀ (L : Type v) [Field L] (c : L) (τ υ : L ≃+* L),
        ¬ Isotopic (famMul r x.1.2 x.1.1) (fun a b : L => a * b - c * τ a * υ b)) := by
  have h3 : (3 : K) ≠ 0 := three_ne_zero_of_card_mod_three hq
  have hr6 := gcd_six_of_prime hr hr5
  have hmod := mod_six_of_gcd_six hr6
  refine ⟨card_famIsotopyClasses hr hr5 hq hfin, ?_, fun x => ?_⟩
  · rw [Nat.card_eq_fintype_card, Module.card_eq_pow_finrank (K := K), hfin]
  obtain ⟨⟨w, σ⟩, hw, hσgen⟩ := x
  have hσ : σ ^ r = 1 := pow_eq_one_of_bij hσgen
  have hP := isPresemifield_famMul hσ hw h3 hmod hr5
  have hgtf : ∀ (L : Type v) [Field L] (c : L) (τ υ : L ≃+* L),
      ¬ Isotopic (famMul r σ w) (fun a b : L => a * b - c * τ a * υ b) := by
    intro L _ c τ υ h
    obtain ⟨c', τ', υ', h'⟩ := isotopic_gtf_transport h
    exact not_isotopic_gtf hr hr5 hq hσgen hw c' τ' υ' h'
  refine ⟨hP, isSemifield_famSemi hP, isotopic_famSemi, fun S hS h => ?_, fun L _ h => ?_, hgtf⟩
  · obtain ⟨h1, h2, h3', h4⟩ := card_nuclei_of_isotopic hq hr5 hr6 hσgen hw hS h
    exact ⟨h4, h1, h2, h3'⟩
  · apply hgtf L 0 (RingEquiv.refl L) (RingEquiv.refl L)
    have : (fun a b : L => a * b - 0 * RingEquiv.refl L a * RingEquiv.refl L b)
        = fun a b : L => a * b := by
      funext a b; simp
    rw [this]
    exact h

end Corollary

section Threshold

/-- **`cor:menichetti`: no base-field threshold repairs the prime-dimensional classification.**
For every prime `r ≥ 5`, every prime `p ≠ 3` and every bound `N` there are finite fields
`K ⊆ F` of characteristic `p` with `|K| > N` and `[F : K] = r`, and a `K`-bilinear semifield
multiplication on `F` (an `r`-dimensional division algebra over `K`) whose centre has exactly
`|K|` elements, which is not isotopic to the field `F` nor to any generalized twisted field on
`F`.  This contradicts the conclusion of Menichetti's Corollary 33 (and Proposition 30).
(Here `|K| = p ^ e` with `e` even; for `p ≡ 1 (mod 3)` every `e ≥ 1` would do.) -/
theorem menichetti_threshold_false (p : ℕ) [Fact p.Prime] (hp3 : p ≠ 3) {r : ℕ}
    (hr : r.Prime) (hr5 : 5 ≤ r) (N : ℕ) :
    ∃ (K F : Type) (_ : Field K) (_ : Fintype K) (_ : Field F) (_ : Fintype F)
      (_ : Algebra K F),
      CharP K p ∧ N < Fintype.card K ∧ Module.finrank K F = r ∧
      ∃ S : F → F → F, IsSemifield S ∧
        (∀ (a : K) (x y : F), S (algebraMap K F a * x) y = algebraMap K F a * S x y) ∧
        (∀ (a : K) (x y : F), S x (algebraMap K F a * y) = algebraMap K F a * S x y) ∧
        Nat.card (semifieldCentre S) = Fintype.card K ∧
        ∀ (c : F) (τ υ : F ≃+* F), ¬ Isotopic S (fun a b : F => a * b - c * τ a * υ b) := by
  haveI : NeZero r := ⟨hr.ne_zero⟩
  have hp := (Fact.out : p.Prime)
  set e := 2 * (N + 1) with he
  have he0 : e ≠ 0 := by omega
  have her0 : e * r ≠ 0 := Nat.mul_ne_zero he0 hr.ne_zero
  letI : Fintype (GaloisField p e) := Fintype.ofFinite _
  letI : Fintype (GaloisField p (e * r)) := Fintype.ofFinite _
  obtain ⟨f⟩ := FiniteField.nonempty_algHom_of_finrank_dvd (F := ZMod p) (K := GaloisField p e)
    (L := GaloisField p (e * r)) (by
      rw [GaloisField.finrank p he0, GaloisField.finrank p her0]
      exact dvd_mul_right e r)
  letI : Algebra (GaloisField p e) (GaloisField p (e * r)) := f.toRingHom.toAlgebra
  haveI : CharP (GaloisField p e) p :=
    charP_of_injective_algebraMap (algebraMap (ZMod p) (GaloisField p e)).injective p
  have hcardK : Fintype.card (GaloisField p e) = p ^ e := by
    rw [← Nat.card_eq_fintype_card, GaloisField.card p e he0]
  have hcardF : Fintype.card (GaloisField p (e * r)) = p ^ (e * r) := by
    rw [← Nat.card_eq_fintype_card, GaloisField.card p (e * r) her0]
  have hq : Fintype.card (GaloisField p e) % 3 = 1 := by
    rw [hcardK, he, pow_mul, Nat.pow_mod]
    have : p ^ 2 % 3 = 1 := by
      have hp3' : p % 3 = 1 ∨ p % 3 = 2 := by
        have : p % 3 ≠ 0 := by
          intro h0
          exact hp3 ((Nat.prime_dvd_prime_iff_eq Nat.prime_three hp).mp
            (Nat.dvd_of_mod_eq_zero h0)).symm
        omega
      rw [Nat.pow_mod]
      rcases hp3' with h | h <;> simp [h]
    rw [this, one_pow]
    norm_num
  have hfin : Module.finrank (GaloisField p e) (GaloisField p (e * r)) = r := by
    have h1 := Module.card_eq_pow_finrank (K := GaloisField p e) (V := GaloisField p (e * r))
    rw [hcardF, hcardK, ← pow_mul] at h1
    have h2 := Nat.pow_right_injective hp.two_le h1
    exact (Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero he0) h2).symm
  refine ⟨GaloisField p e, GaloisField p (e * r), inferInstance, inferInstance, inferInstance,
    inferInstance, inferInstance, inferInstance, ?_, hfin, ?_⟩
  · rw [hcardK]
    calc N < 2 ^ e := by
          have := Nat.lt_two_pow_self (n := e)
          omega
      _ ≤ p ^ e := Nat.pow_le_pow_left hp.two_le e
  have h3 := three_ne_zero_of_card_mod_three hq
  have hr6 := gcd_six_of_prime hr hr5
  have hmod := mod_six_of_gcd_six hr6
  obtain ⟨w, hw⟩ := exists_w_of_card_mod_three hq
  obtain ⟨σ, hσgen⟩ := exists_generator_of_finrank hfin
  have hσ : σ ^ r = 1 := pow_eq_one_of_bij hσgen
  have hP := isPresemifield_famMul hσ hw h3 hmod hr5
  have hS := isSemifield_famSemi hP
  refine ⟨famSemi r σ w, hS, fun a x y => ?_, fun a x y => ?_,
    (card_nuclei_of_isotopic hq hr5 hr6 hσgen hw hS isotopic_famSemi).2.2.2,
    fun c τ υ h => not_isotopic_gtf hr hr5 hq hσgen hw c τ υ (isotopic_famSemi.trans h)⟩
  · have := famSemi_smul_left hP a x y
    simpa only [Algebra.smul_def] using this
  · have := famSemi_smul_right hP a x y
    simpa only [Algebra.smul_def] using this

/-- **`cor:menichetti`, Kaplansky's conjecture.**  The case `r = 5`: for every characteristic
`p ≠ 3` and every bound `N` there is a five-dimensional division algebra over a finite field
`K` of characteristic `p` with `|K| > N`, with centre of order `|K|`, which is isotopic neither
to a field nor to a (generalized) twisted field. -/
theorem kaplansky_counterexample (p : ℕ) [Fact p.Prime] (hp3 : p ≠ 3) (N : ℕ) :
    ∃ (K F : Type) (_ : Field K) (_ : Fintype K) (_ : Field F) (_ : Fintype F)
      (_ : Algebra K F),
      CharP K p ∧ N < Fintype.card K ∧ Module.finrank K F = 5 ∧
      ∃ S : F → F → F, IsSemifield S ∧
        (∀ (a : K) (x y : F), S (algebraMap K F a * x) y = algebraMap K F a * S x y) ∧
        (∀ (a : K) (x y : F), S x (algebraMap K F a * y) = algebraMap K F a * S x y) ∧
        Nat.card (semifieldCentre S) = Fintype.card K ∧
        ∀ (c : F) (τ υ : F ≃+* F), ¬ Isotopic S (fun a b : F => a * b - c * τ a * υ b) :=
  menichetti_threshold_false p hp3 (by norm_num) le_rfl N

end Threshold

end Semifields
