import RequestProject.Linearized
import RequestProject.SemifieldBasics

/-!
# The left idealiser of a generalized twisted field

Let `F / K₀` be a finite Galois extension with cyclic group generated by `σ` of order `n`, and
consider the generalized twisted field multiplication

`x ∘ y = x y - c σ^α(x) σ^β(y)`,   `c ≠ 0`, `α ≠ 0`, `β ≠ 0`, `α ≠ β`.

We show that every `K₀`-linear map in the left idealiser of its spread set is a scalar
multiplication `m_a` with `σ^β (a) = a` (`gtf_leftIdealiser_subset`).  Applied with `K₀` the
prime field (over which every additive map is linear), this is the part of Albert's nuclear
calculation for generalized twisted fields needed to show that an Albert generalized twisted
field isotopic to a member of the family is bilinear over `K = 𝔽_q` (the reduction in the
proof of `thm:nonisotopy`).
-/

namespace Semifields

open scoped BigOperators

variable {K F : Type*} [Field K] [Field F] [Algebra K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F}

/-- The generalized twisted field multiplication `x y - c σ^α(x) σ^β(y)`. -/
def gtfMul (σ : F ≃ₐ[K] F) (c : F) (α β : ZMod n) (x y : F) : F :=
  x * y - c * sig σ α x * sig σ β y

/-- Coefficient extraction for a linearized polynomial with four terms. -/
lemma coeff_four_eq_zero (hinj : Function.Injective (fun i : ZMod n => sig σ i))
    (u₀ u₁ u₂ u₃ : F) (i₀ i₁ i₂ i₃ : ZMod n)
    (h : ∀ x : F, u₀ * sig σ i₀ x + u₁ * sig σ i₁ x + u₂ * sig σ i₂ x + u₃ * sig σ i₃ x = 0)
    (i : ZMod n) :
    (if i₀ = i then u₀ else 0) + (if i₁ = i then u₁ else 0) + (if i₂ = i then u₂ else 0)
      + (if i₃ = i then u₃ else 0) = 0 := by
  classical
  refine sig_coeff_eq_zero hinj (fun i => (if i₀ = i then u₀ else 0) + (if i₁ = i then u₁ else 0)
    + (if i₂ = i then u₂ else 0) + (if i₃ = i then u₃ else 0)) (fun x => ?_) i
  simp only [add_mul, Finset.sum_add_distrib, ite_mul, zero_mul, Finset.sum_ite_eq,
    Finset.mem_univ, if_true]
  exact h x

lemma zmod_eq_of_two_mul_eq_zero {α β : ZMod n} (hα : α ≠ 0) (hβ : β ≠ 0) (h2α : α + α = 0)
    (h2β : β + β = 0) : α = β := by
  have hn : 0 < n := Nat.pos_of_ne_zero (NeZero.ne n)
  have key : ∀ γ : ZMod n, γ ≠ 0 → γ + γ = 0 → 2 * γ.val = n := by
    intro γ hγ h2
    have h1 := congrArg ZMod.val h2
    rw [ZMod.val_add, ZMod.val_zero] at h1
    have hlt := ZMod.val_lt γ
    have hpos : 0 < γ.val := Nat.pos_of_ne_zero (fun h0 => hγ ((ZMod.val_eq_zero γ).mp h0))
    have hdvd : n ∣ γ.val + γ.val := Nat.dvd_of_mod_eq_zero h1
    obtain ⟨k, hk⟩ := hdvd
    have hk1 : k < 2 := by
      by_contra hk2
      push_neg at hk2
      have : n * 2 ≤ n * k := Nat.mul_le_mul_left n hk2
      omega
    interval_cases k <;> omega
  apply ZMod.val_injective
  have := key α hα h2α
  have := key β hβ h2β
  omega

omit [NeZero n] in
lemma gtfMul_add_left (c : F) (α β : ZMod n) (x₁ x₂ y : F) :
    gtfMul σ c α β (x₁ + x₂) y = gtfMul σ c α β x₁ y + gtfMul σ c α β x₂ y := by
  simp only [gtfMul, map_add]; ring

section Main

variable [FiniteDimensional K F]
variable (hbij : Function.Bijective (fun i : ZMod n => sig σ i)) (hfin : Module.finrank K F = n)
  (hσ : σ ^ n = 1)
include hbij hfin hσ

/-- **Idealiser computation for generalized twisted fields.**  If `T` and `g` are `K`-linear
maps with `T (x ∘ y) = x ∘ g (y)`, where `x ∘ y = x y - c σ^α(x) σ^β(y)` with `c ≠ 0`,
`α, β ≠ 0` and `α ≠ β`, then `T` is multiplication by an element fixed by `σ^β`. -/
theorem gtf_idealiser_scalar {c : F} {α β : ZMod n} (hc : c ≠ 0) (hα : α ≠ 0) (hβ : β ≠ 0)
    (hαβ : α ≠ β) (T g : F →ₗ[K] F)
    (hTg : ∀ x y, T (gtfMul σ c α β x y) = gtfMul σ c α β x (g y)) :
    ∃ a : F, (∀ z, T z = a * z) ∧ sig σ β a = a := by
  obtain ⟨t, ht⟩ := exists_sig_expansion hbij.injective hfin T
  obtain ⟨gc, hg⟩ := exists_sig_expansion hbij.injective hfin g
  -- the coefficient identities, one for each index `b` of `y`
  have hE : ∀ x : F, ∀ b : ZMod n,
      t b * sig σ b x + (-(t (b - β) * sig σ (b - β) c)) * sig σ (b - β + α) x
        + (-(gc b)) * sig σ (0 : ZMod n) x + (c * sig σ β (gc (b - β))) * sig σ α x = 0 := by
    intro x
    refine sig_coeff_eq_zero hbij.injective _ (fun y => ?_)
    have hxy := hTg x y
    rw [ht, hg] at hxy
    simp only [gtfMul, map_sub, map_mul, map_sum, Finset.mul_sum, Finset.sum_sub_distrib,
      mul_sub] at hxy
    have r1 : ∑ i, t i * (sig σ i c * sig σ i (sig σ α x) * sig σ i (sig σ β y))
        = ∑ b, t (b - β) * sig σ (b - β) c * sig σ (b - β + α) x * sig σ b y := by
      rw [← (Equiv.subRight β).sum_comp]
      refine Finset.sum_congr rfl (fun i _ => ?_)
      simp only [Equiv.subRight_apply]
      rw [← sig_add_apply hσ, ← sig_add_apply hσ, sub_add_cancel]
      ring
    have r2 : ∑ i, c * sig σ α x * (sig σ β (gc i) * sig σ β (sig σ i y))
        = ∑ b, c * sig σ β (gc (b - β)) * sig σ α x * sig σ b y := by
      rw [← (Equiv.subRight β).sum_comp]
      refine Finset.sum_congr rfl (fun i _ => ?_)
      simp only [Equiv.subRight_apply]
      rw [← sig_add_apply hσ, show β + (i - β) = i by ring]
      ring
    rw [r1, r2] at hxy
    simp only [sig_zero, AlgEquiv.one_apply]
    simp only [add_mul, Finset.sum_add_distrib]
    have s1 : ∑ b, t b * sig σ b x * sig σ b y = ∑ i, t i * (sig σ i x * sig σ i y) :=
      Finset.sum_congr rfl (fun i _ => by ring)
    have s2 : ∑ b, -(t (b - β) * sig σ (b - β) c) * sig σ (b - β + α) x * sig σ b y
        = -∑ b, t (b - β) * sig σ (b - β) c * sig σ (b - β + α) x * sig σ b y := by
      rw [← Finset.sum_neg_distrib]
      exact Finset.sum_congr rfl (fun i _ => by ring)
    have s3 : ∑ b, -gc b * x * sig σ b y = -∑ i, x * (gc i * sig σ i y) := by
      rw [← Finset.sum_neg_distrib]
      exact Finset.sum_congr rfl (fun i _ => by ring)
    rw [s1, s2, s3]
    linear_combination hxy
  have hC := fun b => coeff_four_eq_zero hbij.injective _ _ _ _ _ _ _ _ (fun x => hE x b)
  have hαβ' : α - β ≠ 0 := sub_ne_zero.mpr hαβ
  -- vanishing of `t` away from `0` and `α`
  have F1 : ∀ b, b ≠ 0 → b ≠ α → t b = 0 := by
    intro b hb0 hbα
    have h := hC b b
    have e1 : b - β + α ≠ b := fun h => hαβ (by linear_combination h)
    rw [if_pos rfl, if_neg e1, if_neg (Ne.symm hb0), if_neg (Ne.symm hbα)] at h
    simpa using h
  have F2 : t 0 = gc 0 := by
    have h := hC 0 0
    have e1 : (0 : ZMod n) - β + α ≠ 0 := fun h => hαβ' (by linear_combination h)
    rw [if_pos rfl, if_neg e1, if_pos rfl, if_neg hα] at h
    linear_combination h
  have F3 : sig σ β (t 0) = t 0 := by
    have h := hC β α
    rw [if_neg (Ne.symm hαβ), if_pos (by ring), if_neg (Ne.symm hα), if_pos rfl, sub_self,
      sig_zero, AlgEquiv.one_apply] at h
    have h' : c * (sig σ β (gc 0) - t 0) = 0 := by linear_combination h
    have h'' := sub_eq_zero.mp ((mul_eq_zero.mp h').resolve_left hc)
    rw [← F2] at h''
    exact h''
  have F4' : ∀ b, b ≠ 0 → b - β + α ≠ 0 → gc b = 0 := by
    intro b hb0 hb
    have h := hC b 0
    rw [if_neg hb0, if_pos rfl, if_neg hα, if_neg hb] at h
    linear_combination -h
  have F4'' : ∀ b, b ≠ 0 → b - β + α = 0 → gc b = -(t (b - β) * sig σ (b - β) c) := by
    intro b hb0 hb
    have h := hC b 0
    rw [if_neg hb0, if_pos rfl, if_neg hα, if_pos hb] at h
    linear_combination -h
  have F5 : t α = -(c * sig σ β (gc (α - β))) := by
    have h := hC α α
    have e1 : α - β + α ≠ α := fun h => hαβ (by linear_combination h)
    rw [if_pos rfl, if_neg e1, if_neg (Ne.symm hα), if_pos rfl] at h
    linear_combination h
  have Ftα : t α = 0 := by
    rw [F5]
    by_cases h1 : α - β - β + α = 0
    · rw [F4'' _ hαβ' h1]
      have hmα : α - β - β = -α := by linear_combination h1
      rw [hmα]
      by_cases h2 : -α = α
      · exfalso
        have h2α : α + α = 0 := by linear_combination -h2
        have h2β : β + β = 0 := by linear_combination -h1 + h2α
        exact hαβ (zmod_eq_of_two_mul_eq_zero hα hβ h2α h2β)
      · rw [F1 (-α) (neg_ne_zero.mpr hα) h2]
        simp
    · rw [F4' _ hαβ' h1]
      simp
  refine ⟨t 0, fun z => ?_, F3⟩
  rw [ht, Finset.sum_eq_single (0 : ZMod n)]
  · simp
  · intro b _ hb
    by_cases hbα : b = α
    · rw [hbα, Ftα, zero_mul]
    · rw [F1 b hb hbα, zero_mul]
  · intro h
    exact absurd (Finset.mem_univ _) h

/-- **The left idealiser of a generalized twisted field.**  For `c ≠ 0`, `α, β ≠ 0`,
`α ≠ β` and `x ∘ y = x y - c σ^α(x) σ^β(y)` without zero divisors, every `K`-linear element of
the left idealiser of the spread set is a scalar multiplication `m_a` with `σ^β(a) = a`. -/
theorem gtf_leftIdealiser_subset {c : F} {α β : ZMod n} (hc : c ≠ 0) (hα : α ≠ 0)
    (hβ : β ≠ 0) (hαβ : α ≠ β) (h0 : ∀ x y, gtfMul σ c α β x y = 0 → x = 0 ∨ y = 0)
    {T : F →+ F} (hTK : ∀ (k : K) (z : F), T (algebraMap K F k * z) = algebraMap K F k * T z)
    (hT : T ∈ leftIdealiser (spreadSet (gtfMul σ c α β) (fun y x₁ x₂ =>
      gtfMul_add_left c α β x₁ x₂ y))) :
    ∃ a : F, (∀ z, T z = a * z) ∧ sig σ β a = a := by
  rw [mem_leftIdealiser_spreadSet_iff] at hT
  choose g hg using hT
  -- injectivity of `u ↦ 1 ∘ u`
  have hone : ∀ u v, (∀ x, gtfMul σ c α β x u = gtfMul σ c α β x v) → u = v := by
    intro u v huv
    have e := huv 1
    have : gtfMul σ c α β 1 (u - v) = 0 := by
      simp only [gtfMul, map_sub] at e ⊢
      linear_combination e
    rcases h0 _ _ this with h | h
    · exact absurd h one_ne_zero
    · exact sub_eq_zero.mp h
  have gadd : ∀ y₁ y₂, g (y₁ + y₂) = g y₁ + g y₂ := by
    intro y₁ y₂
    refine hone _ _ (fun x => ?_)
    rw [← hg]
    have e : gtfMul σ c α β x (y₁ + y₂) = gtfMul σ c α β x y₁ + gtfMul σ c α β x y₂ := by
      simp only [gtfMul, map_add]; ring
    rw [e, map_add, hg, hg]
    simp only [gtfMul, map_add]; ring
  have gsmul : ∀ (k : K) y, g (algebraMap K F k * y) = algebraMap K F k * g y := by
    intro k y
    refine hone _ _ (fun x => ?_)
    rw [← hg]
    have e : ∀ u, gtfMul σ c α β x (algebraMap K F k * u)
        = algebraMap K F k * gtfMul σ c α β x u := by
      intro u
      simp only [gtfMul, map_mul, AlgEquiv.commutes]; ring
    rw [e, hTK, hg, e]
  let Tl : F →ₗ[K] F :=
    { toFun := T, map_add' := T.map_add,
      map_smul' := fun k z => by simp only [RingHom.id_apply, Algebra.smul_def]; exact hTK k z }
  let gl : F →ₗ[K] F :=
    { toFun := g, map_add' := gadd,
      map_smul' := fun k z => by simp only [RingHom.id_apply, Algebra.smul_def]; exact gsmul k z }
  exact gtf_idealiser_scalar hbij hfin hσ hc hα hβ hαβ Tl gl (fun x y => hg y x)

end Main

end Semifields
