import RequestProject.Construction

/-!
# Linearized polynomials over a cyclic Galois extension

Let `F / K` be a Galois extension whose Galois group is cyclic of order `n`, generated by
`σ`.  Then the `n` automorphisms `σ^i` form an `F`-basis of the space of `K`-linear
endomorphisms of `F`: every `K`-linear map is uniquely a *linearized polynomial*
`x ↦ ∑ i, c i · σ^i x` (`eq:linearized`).

We also record the corresponding uniqueness statement for `K`-bilinear maps
`F × F → F`, which is the tool used in the computation of the nuclei.
-/

namespace Semifields

open scoped BigOperators

variable {K F : Type*} [Field K] [Field F] [Algebra K F] [FiniteDimensional K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F}

omit [FiniteDimensional K F] in
/-- **Dedekind's independence of characters** in the form needed here: a linearized
polynomial that vanishes identically has zero coefficients. -/
theorem sig_coeff_eq_zero (hinj : Function.Injective (fun i : ZMod n => sig σ i))
    (c : ZMod n → F) (h : ∀ x : F, ∑ i, c i * sig σ i x = 0) : ∀ i, c i = 0 := by
  have hmh : Function.Injective (fun i : ZMod n => ((sig σ i : F ≃ₐ[K] F) : F →* F)) := by
    intro i j hij
    refine hinj ?_
    exact AlgEquiv.ext fun x => congrFun (congrArg (fun f : F →* F => (f : F → F)) hij) x
  have hli := (linearIndependent_monoidHom F F).comp _ hmh
  exact Fintype.linearIndependent_iff.mp hli c (by funext y; simpa using h y)

omit [FiniteDimensional K F] in
/-- The powers of `σ` are `F`-linearly independent in the space of `K`-linear maps. -/
theorem sig_linearIndependent (hinj : Function.Injective (fun i : ZMod n => sig σ i)) :
    LinearIndependent F (fun i : ZMod n => (sig σ i).toLinearMap) := by
  rw [Fintype.linearIndependent_iff]
  intro c hc i
  refine sig_coeff_eq_zero hinj c (fun x => ?_) i
  have := congrArg (fun T : F →ₗ[K] F => T x) hc
  simpa [Algebra.smul_def] using this

/-- **Every `K`-linear endomorphism of `F` is a linearized polynomial** in `σ`. -/
theorem exists_sig_expansion (hinj : Function.Injective (fun i : ZMod n => sig σ i))
    (hfin : Module.finrank K F = n) (T : F →ₗ[K] F) :
    ∃ c : ZMod n → F, ∀ x : F, T x = ∑ i, c i * sig σ i x := by
  have hcard : Fintype.card (ZMod n) = Module.finrank F (F →ₗ[K] F) := by
    rw [ZMod.card, Module.finrank_linearMap K F F F, hfin, Module.finrank_self, mul_one]
  let b := basisOfLinearIndependentOfCardEqFinrank (sig_linearIndependent hinj) hcard
  have hb : ∀ i, b i = (sig σ i).toLinearMap := fun i =>
    congrFun (coe_basisOfLinearIndependentOfCardEqFinrank (sig_linearIndependent hinj) hcard) i
  refine ⟨fun i => b.repr T i, fun x => ?_⟩
  have := b.sum_repr T
  have hx := congrArg (fun S : F →ₗ[K] F => S x) this
  simp only [LinearMap.sum_apply, LinearMap.smul_apply, hb] at hx
  rw [← hx]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [Algebra.smul_def]
  simp

omit [FiniteDimensional K F] in
/-- Uniqueness of the bilinearized expansion of a `K`-bilinear map. -/
theorem sig_bilinear_coeff_eq_zero (hinj : Function.Injective (fun i : ZMod n => sig σ i))
    (c : ZMod n → ZMod n → F)
    (h : ∀ x y : F, ∑ i, ∑ j, c i j * (sig σ i x * sig σ j y) = 0) : ∀ i j, c i j = 0 := by
  have hstep : ∀ x : F, ∀ j, ∑ i, c i j * sig σ i x = 0 := by
    intro x
    refine sig_coeff_eq_zero hinj (fun j => ∑ i, c i j * sig σ i x) (fun y => ?_)
    rw [← h x y, Finset.sum_comm]
    refine Finset.sum_congr rfl (fun j _ => ?_)
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    ring
  intro i j
  exact sig_coeff_eq_zero hinj (fun i => c i j) (fun x => hstep x j) i

end Semifields
