import RequestProject.Admissible
import RequestProject.Idealisers
import RequestProject.Invariance
import RequestProject.Nonisotopy

/-!
# Main results

This file collects the four main theorems of the paper
*Semifields in prime dimensions and counterexamples to Kaplansky's conjecture*
by G. P. Nagy and Y. Zhou:

* `thm_division`         (`thm:division`),
* `thm_invariance`       (`thm:invariance`, for `K`-linear isotopy),
* `thm_direct_nuclei`    (`thm:direct-nuclei`),
* `thm_nonisotopy_field` (`thm:nonisotopy`, finite-field case).

The supporting development is in the other files of this project.  Each statement records
in its own docstring exactly what is and is not covered: `thm_invariance` is proved for
`K`-linear isotopisms, the case on which the paper's general statement rests after the
common semilinearity reduction, and `thm_nonisotopy_field` is the finite-field half of
`thm:nonisotopy`, proved for arbitrary isotopisms; the exclusion of Albert generalized
twisted fields is not formalised here.

## The admissible parameters

Throughout, `K` is a finite field with `|K| ≡ 1 (mod 3)` (the field `𝔽_q` of the paper),
`n ≥ 5` is coprime to `6`, and `F` is a Galois extension of `K` whose Galois group is
cyclic of order `n` generated by `σ`; the last condition is expressed as bijectivity of
`i ↦ σ ^ i` from `ZMod n` onto `Gal (F / K)`, which for `F = 𝔽_{q^n}`, `σ (x) = x ^ (q ^ s)`
is exactly the requirement that `s` be a unit modulo `n`.  Finally `w ∈ K` satisfies
`w ^ 2 - w + 1 = 0`; such a `w` exists by `exists_w_of_card_mod_three`.

The multiplication `eq:construction` of the presemifield `𝒫_{w,s}` is `famMul n σ w`, and
`famMulₗ n σ w` is the same multiplication packaged as a `K`-bilinear map.  Its split
multiplication matrix `L_w(X)` of `eq:family-entries` is `LwM w X`.
-/

namespace Semifields

open scoped BigOperators

section Division

variable {K F : Type*} [Field K] [Fintype K] [Field F] [Algebra K F]
  [FiniteDimensional K F] [IsGalois K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F} {w : K}

/-- **Theorem `thm:division`.**
For all admissible parameters, the algebra `𝒫_{w,s} = (F, +, *_{w,s})` is a presemifield.
Its split left determinant is `det L_w(X) = λ_n(w) ∏ X_i` with
`λ_n(w) = (1 + w^n)^2 (1 - w^{2n}) ≠ 0`; explicitly `λ_n(w) = 3 (1 + w)` if
`n ≡ 1 (mod 6)` and `λ_n(w) = 3 (2 - w)` if `n ≡ 5 (mod 6)`.  Its ordinary-coordinate left
determinant is `λ_n(w) · N_{F/K}`. -/
theorem thm_division (hq : Fintype.card K % 3 = 1) (hn5 : 5 ≤ n) (hn6 : Nat.gcd n 6 = 1)
    (hσgen : Function.Bijective (fun i : ZMod n => sig σ i)) (hw : w ^ 2 - w + 1 = 0) :
    IsPresemifield K (famMulₗ n σ w) ∧
    (LwM (MvPolynomial.C w) (fun i => MvPolynomial.X i)).det
      = MvPolynomial.C (lam w n) * ∏ i : ZMod n, MvPolynomial.X (R := K) i ∧
    lam w n ≠ 0 ∧
    (n % 6 = 1 → lam w n = 3 * (1 + w)) ∧
    (n % 6 = 5 → lam w n = 3 * (2 - w)) ∧
    (∀ x : F, LinearMap.det (famMulₗ n σ w x) = lam w n * Algebra.norm K x) := by
  have hmod := mod_six_of_gcd_six hn6
  have h3 : (3 : K) ≠ 0 := three_ne_zero_of_card_mod_three hq
  have hodd : Odd n := by rcases hmod with h | h <;> exact ⟨n / 2, by omega⟩
  have hcardG : Fintype.card (F ≃ₐ[K] F) = n := by
    rw [← Fintype.card_of_bijective hσgen, ZMod.card]
  have hσ : σ ^ n = 1 := by
    rw [← hcardG]; exact pow_card_eq_one
  refine ⟨isPresemifield_famMul hσ hw h3 hmod hn5, ?_, lam_ne_zero hw h3 hmod,
    fun h => lam_eq_of_mod_one hw h, fun h => lam_eq_of_mod_five hw h, ?_⟩
  · exact det_LwM_mvpoly w hw hodd (by omega)
  · exact fun x => det_famMul_left hσgen hσ hw hodd (by omega) x

end Division

section Nuclei

variable {K F : Type*} [Field K] [Fintype K] [Field F] [Algebra K F]
  [FiniteDimensional K F] [IsGalois K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F} {w : K}

/-- **Theorem `thm:direct-nuclei`.**
For all admissible parameters, the idealisers of the spread set `𝒞` and of the dual spread
set `𝒞^d` of the presemifield `𝒫_{w,s}` are all equal to the set of `K`-scalar
multiplications `m_a : x ↦ a x`, `a ∈ K`:

`I_l(𝒞^d) = I_l(𝒞) = I_r(𝒞) = {m_a : a ∈ K}`.

Here `famCd n σ w` is `𝒞^d = {L_x}` and `famC n σ w` is `𝒞 = {R_y}`, both taken inside the
additive endomorphism ring of `F`, and `scalarMaps K F` is `{m_a : a ∈ K}`. -/
theorem thm_direct_nuclei (hq : Fintype.card K % 3 = 1) (hn5 : 5 ≤ n) (hn6 : Nat.gcd n 6 = 1)
    (hσgen : Function.Bijective (fun i : ZMod n => sig σ i)) (hw : w ^ 2 - w + 1 = 0) :
    leftIdealiser (famCd n σ w) = scalarMaps K F ∧
      leftIdealiser (famC n σ w) = scalarMaps K F ∧
      rightIdealiser (famC n σ w) = scalarMaps K F := by
  have hmod := mod_six_of_gcd_six hn6
  have h3 : (3 : K) ≠ 0 := three_ne_zero_of_card_mod_three hq
  have hcardG : Fintype.card (F ≃ₐ[K] F) = n := by
    rw [← Fintype.card_of_bijective hσgen, ZMod.card]
  have hσ : σ ^ n = 1 := by rw [← hcardG]; exact pow_card_eq_one
  have hfin : Module.finrank K F = n := by
    rw [← IsGalois.card_aut_eq_finrank K F, Nat.card_eq_fintype_card, hcardG]
  have hcn6 : Nat.Coprime n 6 := hn6
  have hcop2 : Nat.Coprime 2 n := (Nat.Coprime.coprime_dvd_right (by norm_num) hcn6).symm
  have hcop3 : Nat.Coprime 3 n := (Nat.Coprime.coprime_dvd_right (by norm_num) hcn6).symm
  have hcop : Nat.Coprime 4 n := by
    have h22 : Nat.Coprime (2 * 2) n := Nat.Coprime.mul_left hcop2 hcop2
    simpa using h22
  have hP := isPresemifield_famMul hσ hw h3 hmod hn5
  exact ⟨leftIdealiser_famCd_eq hσgen hfin hσ hn5 hcop hcop2 hw hP,
    leftIdealiser_famC_eq hσgen hfin hσ hn5 hcop hw hP hcop3,
    rightIdealiser_famC_eq hσgen hfin hσ hn5 hcop hcop2 hw hP⟩

end Nuclei

section Invariance

variable {K : Type*} [Field K] {Ω : Type*} [Field Ω] [Algebra K Ω] {m : ℕ}
variable {mulP mulQ : (Fin m → K) →ₗ[K] (Fin m → K) →ₗ[K] (Fin m → K)}

/-- **Theorem `thm:invariance`** (for `K`-linear isotopy).
The relative determinant profile `eq:relative-profile` is preserved by isotopy between two
presemifields with `K`-bilinear multiplications.  For each of the three determinant types
`μ ∈ {L, R, tr}` the three constituents of the profile are unchanged:

* the component splitting field `E_{μ,K}` of `def:splittingfield`, here `componentField K'`
  computed inside a fixed extension field `Ω` of `K` (take `Ω` an algebraic closure and `K'`
  the image of `K` in it);
* the degrees `d_{μ,K}` of the absolutely irreducible components, here the set
  `absFactorDegrees` of degrees of the irreducible factors;
* the extended determinant-vertex rank `ρ_{μ,K}` of `eq:vertexinvariant`, here the set
  `vertexRanks` of ranks of the pencil at the determinant vertices; it is a single value in
  the linear-component case and is empty exactly when the symbol `⊥` applies.

The hypothesis is a `K`-linear isotopism `(A, B, C)`; this is the `K`-linear case of
`thm:invariance`, on which the general case rests after the common semilinearity reduction
`eq:semilinear-reduction`. -/
theorem thm_invariance
    (hiso : IsotopicLin K (fun x y => mulP x y) (fun x y => mulQ x y)) (K' : Subfield Ω)
    (hK' : ∀ a : K, algebraMap K Ω a ∈ K') :
    (componentField K' (detFormLE (Ω := Ω) (structTensor mulP))
        = componentField K' (detFormLE (Ω := Ω) (structTensor mulQ)) ∧
      absFactorDegrees (detFormLE (Ω := Ω) (structTensor mulP))
        = absFactorDegrees (detFormLE (Ω := Ω) (structTensor mulQ)) ∧
      vertexRanks (detFormLE (Ω := Ω) (structTensor mulP))
          (pencilLat (Ω := Ω) (structTensor mulP))
        = vertexRanks (detFormLE (Ω := Ω) (structTensor mulQ))
          (pencilLat (Ω := Ω) (structTensor mulQ)))
    ∧ (componentField K' (detFormRE (Ω := Ω) (structTensor mulP))
        = componentField K' (detFormRE (Ω := Ω) (structTensor mulQ)) ∧
      absFactorDegrees (detFormRE (Ω := Ω) (structTensor mulP))
        = absFactorDegrees (detFormRE (Ω := Ω) (structTensor mulQ)) ∧
      vertexRanks (detFormRE (Ω := Ω) (structTensor mulP))
          (pencilRat (Ω := Ω) (structTensor mulP))
        = vertexRanks (detFormRE (Ω := Ω) (structTensor mulQ))
          (pencilRat (Ω := Ω) (structTensor mulQ)))
    ∧ (componentField K' (detFormTE (Ω := Ω) (structTensor mulP))
        = componentField K' (detFormTE (Ω := Ω) (structTensor mulQ)) ∧
      absFactorDegrees (detFormTE (Ω := Ω) (structTensor mulP))
        = absFactorDegrees (detFormTE (Ω := Ω) (structTensor mulQ)) ∧
      vertexRanks (detFormTE (Ω := Ω) (structTensor mulP))
          (pencilTat (Ω := Ω) (structTensor mulP))
        = vertexRanks (detFormTE (Ω := Ω) (structTensor mulQ))
          (pencilTat (Ω := Ω) (structTensor mulQ))) := by
  obtain ⟨A, B, Cm, hABC⟩ := hiso
  exact ⟨profile_invariance_left A B Cm hABC K' hK',
    profile_invariance_right A B Cm hABC K' hK',
    profile_invariance_transpose A B Cm hABC K' hK'⟩

end Invariance

section Nonisotopy

variable {K F : Type*} [Field K] [Fintype K] [Field F] [Fintype F] [Algebra K F]
  [FiniteDimensional K F] [IsGalois K F]
variable {n : ℕ} [NeZero n] {σ : F ≃ₐ[K] F} {w : K}

/-- **Theorem `thm:nonisotopy`, finite-field case.**
For all admissible parameters, no member `𝒫_{w,s}` of the family is isotopic to the field
multiplication of `F`.  (Every presemifield isotopic to `𝒫_{w,s}` has `|F|` elements, so a
field of order `|F|` is the only finite field that could occur.)

The proof is the idealiser argument: the left idealiser of the spread set is carried by an
isotopism into the left idealiser of the other spread set, which for the field
multiplication contains all the multiplications `m_a`, `a ∈ F`, while for the family it
consists of the `K`-scalar multiplications only (`thm:direct-nuclei`); and `|F| = |K| ^ n`
exceeds `|K|`.

The remaining assertion of `thm:nonisotopy`, that no member of the family is isotopic to an
Albert generalized twisted field, is not covered by this statement. -/
theorem thm_nonisotopy_field (hq : Fintype.card K % 3 = 1) (hn5 : 5 ≤ n)
    (hn6 : Nat.gcd n 6 = 1) (hσgen : Function.Bijective (fun i : ZMod n => sig σ i))
    (hw : w ^ 2 - w + 1 = 0) :
    ¬ Isotopic (famMul n σ w) (fun x y : F => x * y) :=
  not_isotopic_field hq hn5 hn6 hσgen hw

end Nonisotopy

end Semifields
